### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-redshift#14]
The Component has been blowing its memory recently.
It's currently at 1G, maybe we can boost it a bit.

**Comment by MiroCillik** [comment]
I've boosted it to 2G. Let's see if that helps.. It's probably the query caching.
 In MySQL you can disable it with attribute setting, in Postgres you have to use cursors https://github.com/keboola/db-extractor-pgsql/blob/master/src/Keboola/DbExtractor/Extractor/PgSQL.php#L126 

Not sure how to do it in Redshift :/

**Comment by pivnicek** [comment]
again https://keboola.slack.com/archives/C09U3R1J4/p1542627315002200

**Comment by ErikZigo** [comment]
Mam na to dalsi ticket. Zkusil jsem to navysit na 3GB, ale stejne to nepomohlo :-) Az se mi uvolni ruce, tak to zkusim detailneji zkoumat.

**Comment by ErikZigo** [comment]
ticket: 9471

Maji cca28 mio zaznamu denni prirustek, z toho chteji tahat cca 15mio.
Davam to sem jen abysme vedeli na cem si to muzem nasimulovat a resit

**Comment by ErikZigo** [comment]
Uz to mam nasimulovany.

Podle dokumentace redshiftu se na to taky maji pouzit cursory, stejne jako to Miro udelal v PgSQL ex
https://docs.aws.amazon.com/redshift/latest/dg/declare.html

**Comment by ErikZigo** [comment]
Akorat je tam limitace na velikost resultu pro jednotlive typy nodu.
https://docs.aws.amazon.com/redshift/latest/dg/declare.html#w166aac39b9c81c17b7

to bude stacit kdyz to extractor odchyti a skonci user errorem a nebude se pokouset udelat retry

**Comment by pivnicek** [comment]
Diky za link.  Prvny to bude potreba udelate ten cursor.

**Comment by ErikZigo** [comment]
Akorat na single node cluesteru se to da strankovat max po 1000 zaznamech (viz dokumentace)
Mam rozdelany PR. Prakticky pujde ukradnout kod z naseho pgsql extractoru

**Comment by ErikZigo** [comment]
Tak nakonec se to neobeslo bez problemu.

V projektu kde to driv nepadalo na pameti a stahuji >1mio zaznamu se extrakce vyrazne zpomalila.

50s vs 11 minut u 1,3mio zaznamu jedne tabulky. Extraktor se jim tak z 9minut natahl na 2h40min.
A to jim jeste trikrat vyfailoval diky tomu, ze ta komponenta mela nastaveny timeout jen 1h. Toho jsem si nevsiml.

Koukal jsem na joby od nasazeni tehle upravy a vyfailovalo to pouze u nich.
Ted je zpatky nasazena verze 2.1.8 a taky ale zvysenej timeout komponenty.

**Comment by ErikZigo** [comment]
Takze se nakonec stejne bude asi muset udelat ten UNLOAD do S3
https://github.com/keboola/db-extractor-redshift/issues/20

Pripadne zkusit pouzit JDBC https://docs.aws.amazon.com/redshift/latest/dg/declare.html#declare-performance

**Comment by ErikZigo** [comment]
Zvazuju ze by se v2.2.0 nasadila bokem jako novy extractor. Pro lidi, kterym to proste failuje na pameti.

Asi by nebyl problem tam dodelat i pokus nastavit vetsi davku nez jen 1000 s tim, ze by to automaticky fallbackovalo na tech zakladnich 1000 co redshift povoluje u single node clusteru.

**Comment by MiroCillik** [comment]
Hmm, to je dost vyrazne spomalenie :( 
Nasadit to bokem by bolo fajn ako docasne riesenie, pre ludi, ktorym to pada na pameti.

**Comment by ErikZigo** [comment]
@MiroCillik mi nedoslo jak to ted funguje, ze to redshift ex sice fetchuje po radku, ale cely vysledek ma nacteny v pameti. Takze je to okamzite, oproti tomu davkovymu zpracovani.

Do ticketu tech, kterym to padalo na pameti jsem napsal jestli pockaj a nebo jestli jim neco hori, tak ze jim nasadim ten ex bokem.

**Comment by ErikZigo** [comment]
Zatim to poustim z hlavy dokud nebudu mit odpoved na ticket.

Dneska jsem si zkousel akorat jake davky to snese. Kdyz by na to prislo, asi bych to udelal fakt konfigurovatelne na urovni DB EX

**Comment by ErikZigo** [comment]
Tohle issue zaviram:

Je k dispozici `keboola.ex-db-redshift-cursors` appka ktera stahuje data pomoci kurzoru.
Spravna cesta je ale pres UNLOAD do S3 a to ma samostatne issue https://github.com/keboola/db-extractor-redshift/issues/20
