### ISSUE TITLE
Tests credentials with SSH tunnel error

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-redshift#4]
![image](https://user-images.githubusercontent.com/903531/27031082-1669a06a-4f6f-11e7-89f1-9cd1e0e3118e.png)

![image](https://user-images.githubusercontent.com/903531/27031090-23459ff0-4f6f-11e7-8d86-0433bdbf0388.png)

**Comment by Halama** [comment]
https://connection.keboola.com/admin/utils/logs?file=2017/06/12/12/2017-06-12-12-58-07-593e73bf9ef95-log

**Comment by pivnicek** [comment]
fixed in https://github.com/keboola/db-extractor-redshift/releases/tag/1.0.3
